spring:
  redis:
    host: localhost
    port: 6379
  #  cloud:
  #    gcp:
  #      storage:
  #        credentials:
  #          location: nosell-3c87ec8cfb7f.json
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          naver:
  #            client-id : [CLIENT_ID]
  #            client-secret : [CLIENT_SECRET]
  #            redirectUriTemplate : "http://localhost:8080/login/oauth2/code/naver"
  #            authorization-grant-type : authorization_code
  #            scope : name, email, profile_image
  #            client-name : Naver
  #        provider:
  #          naver:
  #            authorization-uri : https://nid.naver.com/oauth2.0/authorize
  #            token-uri : https://nid.naver.com/oauth2.0/token
  #            user-info-uri : https://openapi.naver.com/v1/nid/me
  #            user-name-attribute : response
  #
  #          google:
  #            client-id: 147280823959-i6o47rvpm0173at1dcstg24ne70amaas.apps.googleusercontent.com
  #            client-secret: imBng1TlDEC5CmkI3wBpkaYy
  #            #redirectUri:
  #            scope: email, profile # 로그인 성공 후 구글에 요청할 사용자 정보
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/hellomarket?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    name: root
    password: hellomarket
    driver-class-name: org.mariadb.jdbc.Driver
    platform: mysql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

server:
  port: 80

rest:
  maxConnTotal: 50
  maxConnPerRoute: 10
  setConnectTimeout: 3000
  readTimeout: 5000