spring:
  profiles:
    active: local
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  datasource:
    url: jdbc:h2:tcp://localhost/~/moon
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

