jwt:
  header: Authorization
  #  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

sns:
  google:
    userinfo:
      url: https://www.googleapis.com/oauth2/v2/userinfo
    token:
      url: https://oauth2.googleapis.com/token
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 147280823959-i6o47rvpm0173at1dcstg24ne70amaas.apps.googleusercontent.com
      secret: imBng1TlDEC5CmkI3wBpkaYy
    callback:
      url: http://localhost:8080/api/v1/auth/google/callback

