INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) values (2, 'ROLE_ADMIN');

-- ID : nosell@nosell.com
-- PW : nosell
INSERT INTO USER
VALUES
(
    1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'nosell@nosell.com', CURRENT_TIMESTAMP(), 'nickname', 0,
    '$2a$10$ns9gjAMzHcBYVsLg9kHKE.QRs/EtY7L8jFfQsAD9F5Rvvt/jy0MUi',
    CURRENT_TIMESTAMP(), '01000000000', 'profile_image','ACTIVE');


INSERT INTO USER_AUTHORITY
VALUES
(1,1,1);