-- 유저
INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
values (NOW(), NOW(), 'ROLE_USER');

INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
values (NOW(), NOW(), 'ROLE_ADMIN');

-- ID : nosell@nosell.com
-- PW : nosell
INSERT INTO USER
VALUES
(
    1, NOW(), NOW(), 'nosell@nosell.com', NOW(), 'nickNAME', 0,
    '$2a$10$ns9gjAMzHcBYVsLg9kHKE.QRs/EtY7L8jFfQsAD9F5Rvvt/jy0MUi',
    NOW(), '01000000000', 'profile_image','ACTIVE');


INSERT INTO USER_AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_ID, USER_ID)
VALUES
(NOW(), NOW(),1,1);

------------------------------------------------------------------------------------------

--카테고리

--대분류
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '패션의류',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '패션잡화',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '유아용품',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '가구/생활',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '취미/컬렉션',0);

INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '디지털/가전',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '스포츠/레저',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '뷰티/미용',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '반려동식물용품',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '자동차/공구',0);

INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '도서/굿즈',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '기타', 0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '무료나눔', 0);

--중분류
--패션의류
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '여성의류',1);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '남성의류',1);

--패션잡화
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '신발/가방',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '패션잡화',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '쥬얼리',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '명품',2);

--유아용품
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '출산/육아',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '장난감/완구',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '유아동의류/잡화',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '유아동생활용품',3);

--가구/생활
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '생활용품',4);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '가구/소품DIY',4);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '주방/욕실',4);

--취미/컬렉션
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '골동품/희귀품',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), 'RC카/드론',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '피규어/키덜트',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '게임/악기',5);

--디지털/가전
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '핸드폰/태블릿',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '노트북/PC/주변기기',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '카메라/음향기기',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '게임/악기',6);

--스포츠/레저
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '여행/숙발',7);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '스포츠용품',7);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '레저용품',7);

--뷰티/미용
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '화장품/향수',8);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '바디/헤어',8);

--반려동식물용품
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '동물용품',9);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '식물용품',9);

--자동차/공구
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '자동차용품',10);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '바이크용품',10);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '공구/안전/산업용품',10);

--도서/굿즈
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '도서/문구',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '스타굿즈/티켓',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), 'CD/DVD',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '미술용품/상품권',11);

--기타
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '부동산',12);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '건강/의료',12);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '재능/서비스',12);

--무료나눔
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '생활용품',13);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(NOW(), NOW(), '식품/기타',13);

------------------------------------------------------------------------------------------------------------------------

-- 1줄(4)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '여성의류 팝니다.', 14, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 1, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '남성의류 팝니다.', 15, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 2, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '신발/가방 팝니다.', 16, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 3, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '패션잡화 팝니다.', 17, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 4, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 2줄(8)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '쥬얼리 팝니다.', 18, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 5, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '명품 팝니다.', 19, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 6, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '출산/육아 팝니다.', 20, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 7, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '장난감/완구/팝니다.', 21, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 8, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 3줄(12)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '유아동의류/잡화 팝니다.', 22, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 9, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '유아동생활용품 팝니다.', 23, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 10, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '생활용품 팝니다.', 24, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 11, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '가구/소품DIY 팝니다.', 25, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 12, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 4줄(16)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '주방/욕실 팝니다.', 26, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 13, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '골동품/희귀품 팝니다.', 27, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 14, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', 'RC카/드론 팝니다.', 28, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 15, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '피규어/키덜트 팝니다.', 29, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 16, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 5줄(20)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '게임/악기 팝니다.', 30, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 17, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '핸드폰/태블릿 팝니다.', 31, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 18, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '노트북/PC/주변기기 팝니다.', 32, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 19, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '카메라/음향기기 팝니다.', 33, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 20, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 6줄(24)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '게임/악기 팝니다.', 34, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 21, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '여행/숙발 팝니다.', 35, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 22, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '스포츠용품 팝니다.', 36, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 23, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '레저용품 팝니다.', 37, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 24, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 7줄(28)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '화장품/향수 팝니다.', 38, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 25, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '바디/헤어 팝니다.', 39, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 26, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '동물용품 팝니다.', 40, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 27, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '식물용품 팝니다.', 41, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 28, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 8줄(32)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '자동차용품 팝니다.', 42, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 29, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '바이크용품 팝니다.', 43, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 30, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '공구/안전/산업용품 팝니다.', 44, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 31, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '도서/문구 팝니다.', 45, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 32, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 9줄(36)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '자동차용품 팝니다.', 42, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 33, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '바이크용품 팝니다.', 43, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 34, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '공구/안전/산업용품 팝니다.', 44, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 35, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '도서/문구 팝니다.', 45, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 36, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 10줄(40)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '스타굿즈/티켓 팝니다.', 46, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 37, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', 'CD/DVD 팝니다.', 47, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 38, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '미술용품/상품권.', 48, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 39, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '부동산 팝니다.', 49, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 40, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

-- 11줄(44)
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'NO_SELL', 'PARCEL', '내용', 10000, 'NEW', 'SALE', '건강/의료 팝니다.', 50, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 41, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 13000, 'NEW', 'SALE', '재능/서비스 팝니다.', 51, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 42, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 15000, 'NEW', 'SALE', '생활용품 팝니다.', 52, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 43, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(NOW(), NOW(), 'DIRECT_DEAL', 'PARCEL', '내용', 17000, 'NEW', 'SALE', '식품/기타 팝니다.', 53, 1);
INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(NOW(), NOW(), 44, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

