--drop all objects : H2 테이블 전체삭제

-- 유저
INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
values (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ROLE_USER');

INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
 values (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ROLE_ADMIN');

-- ID : nosell@nosell.com
-- PW : nosell
INSERT INTO USER
VALUES
(
    1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'nosell@nosell.com', CURRENT_TIMESTAMP(), 'nickNAME', 0,
    '$2a$10$ns9gjAMzHcBYVsLg9kHKE.QRs/EtY7L8jFfQsAD9F5Rvvt/jy0MUi',
    CURRENT_TIMESTAMP(), '01000000000', 'profile_image','ACTIVE');


INSERT INTO USER_AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_ID, USER_ID)
VALUES
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),1,1);

------------------------------
--카테고리

--대분류
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '패션의류',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '패션잡화',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '유아용품',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '가구/생활',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '취미/컬렉션',0);

INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '디지털/가전',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '스포츠/레저',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '뷰티/미용',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '반려동식물용품',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '자동차/공구',0);

INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '도서/굿즈',0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '기타', 0);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '무료나눔', 0);

--중분류
--패션의류
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '여성의류',1);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '남성의류',1);

--패션잡화
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '신발/가방',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '패션잡화',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '쥬얼리',2);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '명품',2);

--유아용품
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '출산/육아',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '장난감/완구',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '유아동의류/잡화',3);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '유아동생활용품',3);

--가구/생활
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '생활용품',4);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '가구/소품DIY',4);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '주방/욕실',4);

--취미/컬렉션
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '골동품/희귀품',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'RC카/드론',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '피규어/키덜트',5);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '게임/악기',5);

--디지털/가전
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '핸드폰/태블릿',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '노트북/PC/주변기기',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '카메라/음향기기',6);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '게임/악기',6);

--스포츠/레저
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '여행/숙발',7);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '스포츠용품',7);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '레저용품',7);

--뷰티/미용
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '화장품/향수',8);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '바디/헤어',8);

--반려동식물용품
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '동물용품',9);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '식물용품',9);

--자동차/공구
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '자동차용품',10);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '바이크용품',10);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '공구/안전/산업용품',10);

--도서/굿즈
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '도서/문구',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '스타굿즈/티켓',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CD/DVD',11);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '미술용품/상품권',11);

--기타
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '부동산',12);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '건강/의료',12);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '재능/서비스',12);

--무료나눔
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '생활용품',13);
INSERT INTO CATEGORY(CREATED_AT, UPDATED_AT, NAME, PARENT_ID) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '식품/기타',13);

------------------------------
--상품
INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 10개

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 20개

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 30개

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 40개

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 50개