--상품
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);

INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);

INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'https://user-images.githubusercontent.com/52563841/107608509-88ff2100-6c7f-11eb-8629-9859c9167d31.jpg');

INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'https://user-images.githubusercontent.com/52563841/107608535-96b4a680-6c7f-11eb-9980-5cc622c6c872.png');

INSERT INTO PRODUCT_IMAGE(CREATED_AT, UPDATED_AT, PRODUCT_ID, IMAGE_URL)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'https://user-images.githubusercontent.com/52563841/107608551-9fa57800-6c7f-11eb-8ff7-14176b5ee074.PNG');

---





-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- ---- 10개
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- ---- 20개
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- ---- 30개
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- ---- 40개
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), PARSEDATETIME ('2016-11-17 12:00:00','yyyy-MM-dd hh:mm:ss'), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 14, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 15, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 16, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 17, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 18, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIRECT_DEAL', 'PARCEL', '설명', 10000, 'NEW', 'SALE', '제목', 19, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ONLINE', 'DIRECT_PICKUP', '설명', 10000, 'OLD', 'SALE', '제목', 20, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);
--
-- INSERT INTO PRODUCT(CREATED_AT, UPDATED_AT, DEAL_TYPE, DELIVERY_TYPE, DESCRIPTION, PRICE, PRODUCT_STATUS, SALES_STATUS, TITLE, CATEGORY_ID, USER_ID)
-- VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NO_SELL', 'DIRECT_PICKUP', '설명', 10000, 'USED', 'SALE', '제목', 21, 1);

---- 50개